env:
  browser: true
  commonjs: true
  es2021: true
overrides: []
parserOptions:
  ecmaVersion: latest
rules: {
  no-console: 0,
  import/extensions:
    - error,
    - ignorePackages,
    - js: always
}
